src/Entity/EmailMessage.php
<?php

namespace App\Entity;

use App\Repository\EmailMessageRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EmailMessageRepository::class)]
class EmailMessage
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $email_key = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $subject = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $body = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmailKey(): ?string
    {
        return $this->email_key;
    }

    public function setEmailKey(string $email_key): static
    {
        $this->email_key = $email_key;

        return $this;
    }

    public function getSubject(): ?string
    {
        return $this->subject;
    }

    public function setSubject(?string $subject): static
    {
        $this->subject = $subject;

        return $this;
    }

    public function getBody(): ?string
    {
        return $this->body;
    }

    public function setBody(?string $body): static
    {
        $this->body = $body;

        return $this;
    }
}

src/Form/EmailMessageType.php
<?php

namespace App\Form;

use App\Entity\EmailMessage;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EmailMessageType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('email_key')
            ->add('subject')
            ->add('body')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => EmailMessage::class,
        ]);
    }
}

src/Controller/EmailMessageController.php
<?php

namespace App\Controller;

use App\Entity\EmailMessage;
use App\Form\EmailMessageType;
use App\Repository\EmailMessageRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('{_locale<%app.supported_locales%>}/email-message')]
class EmailMessageController extends AbstractController
{
    #[Route('/', name: 'app_email_message_index', methods: ['GET'])]
    public function index(EmailMessageRepository $emailMessageRepository): Response
    {
        return $this->render('email_message/index.html.twig', [
            'email_messages' => $emailMessageRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_email_message_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $emailMessage = new EmailMessage();
        $form = $this->createForm(EmailMessageType::class, $emailMessage);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($emailMessage);
            $entityManager->flush();

            return $this->redirectToRoute('app_email_message_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('email_message/new.html.twig', [
            'email_message' => $emailMessage,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_email_message_show', methods: ['GET'])]
    public function show(EmailMessage $emailMessage): Response
    {
        return $this->render('email_message/show.html.twig', [
            'email_message' => $emailMessage,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_email_message_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, EmailMessage $emailMessage, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(EmailMessageType::class, $emailMessage);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_email_message_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('email_message/edit.html.twig', [
            'email_message' => $emailMessage,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_email_message_delete', methods: ['POST'])]
    public function delete(Request $request, EmailMessage $emailMessage, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$emailMessage->getId(), $request->request->get('_token'))) {
            $entityManager->remove($emailMessage);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_email_message_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/email_message/_delete_form.html.twig
<form method="post" action="{{ path('app_email_message_delete', {'id': email_message.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ email_message.id) }}">
    <button class="btn">Delete</button>
</form>

templates/email_message/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit EmailMessage{% endblock %}

{% block body %}
    <h1>Edit EmailMessage</h1>

    {{ include('email_message/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_email_message_index') }}">back to list</a>

    {{ include('email_message/_delete_form.html.twig') }}
{% endblock %}

templates/email_message/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}EmailMessage index{% endblock %}

{% block body %}
    <div
		class="col-xxl-8 order-2 order-xxl-1">
		<!--begin::Advance Table Widget 2-->
		<div
			class="card card-custom card-stretch gutter-b">
			<!--begin::Header-->
			<div class="card-header border-0 pt-5">
				<h3 class="card-title align-items-start flex-column">
					<span class="card-label font-weight-bolder text-dark">Facility</span>
					<span class="text-muted mt-3 font-weight-bold font-size-sm">Lists</span>
				</h3>
    <a href="{{ path('app_email_message_new') }}">Create new</a>
  
			</div> 
			<div
				class="card-body pt-3 pb-0">
				<!--begin::Table-->
				<div class="table-responsive">
 <table class="table table-bordered">  <thead>
            <tr>
                <th>Id</th>
                <th>Email_key</th>
                <th>Subject</th>
                <th>Body</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for email_message in email_messages %}
            <tr>
                <td>{{ email_message.id }}</td>
                <td>{{ email_message.emailKey }}</td>
                <td>{{ email_message.subject }}</td>
                <td>{{ email_message.body }}</td>
                <td>
                    <a href="{{ path('app_email_message_show', {'id': email_message.id}) }}">show</a>
                    <a href="{{ path('app_email_message_edit', {'id': email_message.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>


</div>
				<!--end::Table-->
			</div>
			<!--end::Body-->
		</div>
	</div>{% endblock %}

templates/email_message/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New EmailMessage{% endblock %}

{% block body %}
    <h1>Create new EmailMessage</h1>

    {{ include('email_message/_form.html.twig') }}

    <a href="{{ path('app_email_message_index') }}">back to list</a>
{% endblock %}

templates/email_message/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}EmailMessage{% endblock %}

{% block body %}
    <h1>EmailMessage</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ email_message.id }}</td>
            </tr>
            <tr>
                <th>Email_key</th>
                <td>{{ email_message.emailKey }}</td>
            </tr>
            <tr>
                <th>Subject</th>
                <td>{{ email_message.subject }}</td>
            </tr>
            <tr>
                <th>Body</th>
                <td>{{ email_message.body }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_email_message_index') }}">back to list</a>

    <a href="{{ path('app_email_message_edit', {'id': email_message.id}) }}">edit</a>

    {{ include('email_message/_delete_form.html.twig') }}
{% endblock %}